# Generated by Django 2.2 on 2019-07-10 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_name', models.CharField(max_length=50, null=True)),
                ('marathi_name', models.CharField(max_length=50, null=True)),
                ('alias', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessPoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(max_length=50)),
                ('english', models.CharField(max_length=100)),
                ('marathi', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_type', models.CharField(choices=[(1, 'business'), (2, 'service'), (3, 'classes')], max_length=50)),
                ('business_name_english', models.CharField(max_length=100)),
                ('business_name_marathi', models.CharField(max_length=100)),
                ('business_contact_number', models.CharField(max_length=10)),
                ('start_time', models.TimeField(null=True)),
                ('end_time', models.TimeField(null=True)),
                ('weekly_off', models.CharField(max_length=15, null=True)),
                ('business_point_1', models.CharField(max_length=150, null=True)),
                ('business_point_2', models.CharField(max_length=150, null=True)),
                ('business_point_3', models.CharField(max_length=150, null=True)),
                ('business_address', models.CharField(max_length=100, null=True)),
                ('discount', models.PositiveSmallIntegerField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('business_image', models.ImageField(null=True, upload_to='business_images')),
                ('likes_counter', models.PositiveIntegerField(default=0)),
                ('city', models.CharField(max_length=50, null=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=8, null=True)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=8, null=True)),
                ('is_payment_made', models.BooleanField(default=False)),
                ('payment_amount', models.PositiveIntegerField(null=True)),
                ('valid_till', models.DateTimeField(null=True)),
                ('are_details_complete', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('business_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BusinessPostApp.BusinessCategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.User')),
            ],
        ),
    ]
