# Generated by Django 2.2 on 2019-07-10 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessPostApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=100)),
                ('amount', models.PositiveIntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=False)),
                ('failure_reason', models.CharField(max_length=200, null=True)),
                ('business_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BusinessPostApp.BusinessPost')),
            ],
        ),
    ]
