# Generated by Django 2.2.2 on 2019-07-19 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessPostApp', '0002_paymenttransactions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businesscategory',
            old_name='alias',
            new_name='alias1',
        ),
        migrations.AddField(
            model_name='businesscategory',
            name='alias2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='businesscategory',
            name='alias3',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='businesscategory',
            name='alias4',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='businesscategory',
            name='alias5',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='businesscategory',
            name='english_name',
            field=models.CharField(max_length=50),
        ),
    ]
