# Generated by Django 2.2.2 on 2019-07-24 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessPostApp', '0003_auto_20190719_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesspost',
            name='business_name_marathi',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
