# Generated by Django 2.2.2 on 2019-08-06 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessPostApp', '0009_auto_20190724_1627'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businesspost',
            old_name='business_category',
            new_name='business_category_id',
        ),
        migrations.RenameField(
            model_name='businesspost',
            old_name='user',
            new_name='user_id',
        ),
    ]
