# Generated by Django 2.2.2 on 2019-08-06 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessPostApp', '0010_auto_20190806_2126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businesspost',
            old_name='user_id',
            new_name='User',
        ),
    ]
