# Generated by Django 2.2.2 on 2019-08-06 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessPostApp', '0011_auto_20190806_2135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businesspost',
            old_name='business_category_id',
            new_name='business_category',
        ),
    ]
