# Generated by Django 2.2.2 on 2019-08-06 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessPostApp', '0012_auto_20190806_2136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businesspost',
            old_name='User',
            new_name='user',
        ),
    ]
