# Generated by Django 2.2.2 on 2019-08-06 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessPostApp', '0013_auto_20190806_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesspost',
            name='likes_counter',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
